-- =========================================
-- ORACLE DATABASE SETUP
-- =========================================

-- CREATE TABLES
-- =========================================

CREATE TABLE departments (
department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
department_name VARCHAR2(100)
);

CREATE TABLE employees (
employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
email VARCHAR2(100),
salary NUMBER(10,2),
hire_date DATE,
department_id NUMBER,
CONSTRAINT fk_emp_dept
FOREIGN KEY (department_id)
REFERENCES departments(department_id)
);

CREATE TABLE customers (
customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_name VARCHAR2(100),
email VARCHAR2(100),
city VARCHAR2(100),
country VARCHAR2(100)
);

CREATE TABLE products (
product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name VARCHAR2(100),
category VARCHAR2(100),
price NUMBER(10,2),
stock_quantity NUMBER
);

CREATE TABLE orders (
order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id NUMBER,
order_date DATE,
total_amount NUMBER(10,2),
CONSTRAINT fk_order_customer
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id NUMBER,
product_id NUMBER,
quantity NUMBER,
subtotal NUMBER(10,2),

```
CONSTRAINT fk_orderitem_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

CONSTRAINT fk_orderitem_product
    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
```

);

CREATE TABLE payments (
payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id NUMBER,
payment_method VARCHAR2(50),
payment_date DATE,
amount NUMBER(10,2),

```
CONSTRAINT fk_payment_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
```

);

-- =========================================
-- INSERT DEPARTMENTS
-- =========================================

INSERT INTO departments (department_name) VALUES ('HR');
INSERT INTO departments (department_name) VALUES ('IT');
INSERT INTO departments (department_name) VALUES ('Finance');
INSERT INTO departments (department_name) VALUES ('Sales');
INSERT INTO departments (department_name) VALUES ('Marketing');

-- =========================================
-- INSERT EMPLOYEES
-- =========================================

INSERT INTO employees
(first_name,last_name,email,salary,hire_date,department_id)
VALUES
('John','Smith','[john@gmail.com](mailto:john@gmail.com)',60000,
TO_DATE('2023-01-10','YYYY-MM-DD'),2);

INSERT INTO employees
(first_name,last_name,email,salary,hire_date,department_id)
VALUES
('Alice','Brown','[alice@gmail.com](mailto:alice@gmail.com)',55000,
TO_DATE('2022-06-15','YYYY-MM-DD'),1);

INSERT INTO employees
(first_name,last_name,email,salary,hire_date,department_id)
VALUES
('David','Wilson','[david@gmail.com](mailto:david@gmail.com)',75000,
TO_DATE('2021-03-20','YYYY-MM-DD'),3);

INSERT INTO employees
(first_name,last_name,email,salary,hire_date,department_id)
VALUES
('Emma','Taylor','[emma@gmail.com](mailto:emma@gmail.com)',50000,
TO_DATE('2024-02-01','YYYY-MM-DD'),4);

-- =========================================
-- INSERT CUSTOMERS
-- =========================================

INSERT INTO customers
(customer_name,email,city,country)
VALUES
('Raj Sharma','[raj@gmail.com](mailto:raj@gmail.com)','Delhi','India');

INSERT INTO customers
(customer_name,email,city,country)
VALUES
('Sarah Johnson','[sarah@gmail.com](mailto:sarah@gmail.com)','New York','USA');

INSERT INTO customers
(customer_name,email,city,country)
VALUES
('Mohit Verma','[mohit@gmail.com](mailto:mohit@gmail.com)','Mumbai','India');

INSERT INTO customers
(customer_name,email,city,country)
VALUES
('Lisa White','[lisa@gmail.com](mailto:lisa@gmail.com)','London','UK');

-- =========================================
-- INSERT PRODUCTS
-- =========================================

INSERT INTO products
(product_name,category,price,stock_quantity)
VALUES
('Laptop','Electronics',75000,10);

INSERT INTO products
(product_name,category,price,stock_quantity)
VALUES
('Phone','Electronics',30000,20);

INSERT INTO products
(product_name,category,price,stock_quantity)
VALUES
('Keyboard','Accessories',1500,50);

INSERT INTO products
(product_name,category,price,stock_quantity)
VALUES
('Mouse','Accessories',800,100);

-- =========================================
-- INSERT ORDERS
-- =========================================

INSERT INTO orders
(customer_id,order_date,total_amount)
VALUES
(1,TO_DATE('2025-01-10','YYYY-MM-DD'),75800);

INSERT INTO orders
(customer_id,order_date,total_amount)
VALUES
(2,TO_DATE('2025-01-12','YYYY-MM-DD'),30000);

INSERT INTO orders
(customer_id,order_date,total_amount)
VALUES
(3,TO_DATE('2025-01-15','YYYY-MM-DD'),13500);

-- =========================================
-- INSERT ORDER ITEMS
-- =========================================

INSERT INTO order_items
(order_id,product_id,quantity,subtotal)
VALUES
(1,1,1,75000);

INSERT INTO order_items
(order_id,product_id,quantity,subtotal)
VALUES
(1,4,1,800);

INSERT INTO order_items
(order_id,product_id,quantity,subtotal)
VALUES
(2,2,1,30000);

-- =========================================
-- INSERT PAYMENTS
-- =========================================

INSERT INTO payments
(order_id,payment_method,payment_date,amount)
VALUES
(1,'Credit Card',
TO_DATE('2025-01-10','YYYY-MM-DD'),
75800);

INSERT INTO payments
(order_id,payment_method,payment_date,amount)
VALUES
(2,'UPI',
TO_DATE('2025-01-12','YYYY-MM-DD'),
30000);

-- =========================================
-- COMMIT
-- =========================================

COMMIT;

-- =========================================
-- PRACTICE QUERIES
-- =========================================

-- 1. INNER JOIN

SELECT
c.customer_name,
o.order_id,
o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

-- =========================================

-- 2. GROUP BY

SELECT
country,
COUNT(*) AS total_customers
FROM customers
GROUP BY country;

-- =========================================

-- 3. HAVING

SELECT
customer_id,
SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id
HAVING SUM(total_amount) > 50000;

-- =========================================

-- 4. SUBQUERY

SELECT
product_name,
price
FROM products
WHERE price >
(
SELECT AVG(price)
FROM products
);

-- =========================================

-- 5. WINDOW FUNCTION

SELECT
employee_id,
first_name,
salary,
RANK() OVER (ORDER BY salary DESC) salary_rank
FROM employees;

-- =========================================

-- 6. VIEW

CREATE OR REPLACE VIEW customer_orders AS
SELECT
c.customer_name,
o.order_id,
o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

-- =========================================

-- 7. INDEX

CREATE INDEX idx_customer_email
ON customers(email);

-- =========================================

-- 8. STORED PROCEDURE

CREATE OR REPLACE PROCEDURE GetCustomerOrders(
p_customer_id IN NUMBER
)
AS
BEGIN
FOR rec IN
(
SELECT *
FROM orders
WHERE customer_id = p_customer_id
)
LOOP
DBMS_OUTPUT.PUT_LINE(
'Order ID: ' || rec.order_id ||
' Amount: ' || rec.total_amount
);
END LOOP;
END;
/

-- =========================================

-- 9. TOP SALARY EMPLOYEES

SELECT *
FROM
(
SELECT *
FROM employees
ORDER BY salary DESC
)
WHERE ROWNUM <= 5;

-- =========================================

-- 10. TOTAL SALES BY COUNTRY

SELECT
c.country,
SUM(o.total_amount) AS total_sales
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.country;

-- =========================================

-- 11. MOST SOLD PRODUCTS

SELECT
p.product_name,
SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC;

-- =========================================

-- 12. RUNNING TOTAL

SELECT
order_id,
total_amount,
SUM(total_amount)
OVER (ORDER BY order_date)
AS running_total
FROM orders;

-- =========================================

-- 13. DENSE RANK

SELECT
first_name,
salary,
DENSE_RANK()
OVER (ORDER BY salary DESC)
AS salary_rank
FROM employees;

-- =========================================

-- 14. PRODUCTS NEVER ORDERED

SELECT product_name
FROM products
WHERE product_id NOT IN
(
SELECT DISTINCT product_id
FROM order_items
);

-- =========================================

-- 15. TOTAL ORDERS PER CUSTOMER

SELECT
c.customer_name,
COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;
